#!/usr/bin/env bash
set -euo pipefail

# 将每条线路各自的 cn.yaml fragment 合并为一份供唯一 GOST 进程读取的配置。
# 用法: compile-config.sh OUTPUT ROUTE_FRAGMENT...
OUTPUT="${1:-}"
[[ -n "$OUTPUT" ]] || { echo "usage: $0 OUTPUT ROUTE_FRAGMENT..." >&2; exit 2; }
shift
(( $# > 0 )) || { echo "at least one route fragment is required" >&2; exit 2; }

seen_routes=" "
for fragment in "$@"; do
    [[ -r "$fragment" ]] || { echo "route fragment not readable: $fragment" >&2; exit 1; }
    route="$(awk '/^# pathlock-route:[[:space:]]*/ { sub(/^# pathlock-route:[[:space:]]*/, ""); print; exit }' "$fragment")"
    [[ "$route" =~ ^[A-Za-z0-9][A-Za-z0-9_-]{0,31}$ ]] || {
        echo "invalid or missing route marker: $fragment" >&2
        exit 1
    }
    [[ "$seen_routes" != *" $route "* ]] || { echo "duplicate route id: $route" >&2; exit 1; }
    seen_routes+="$route "

    # Fragment 是线路故障域的边界：它只能定义并引用自己的 chain，且必须
    # 包含本线路唯一的 Anchor。不能仅因聚合配置里存在另一线路的 chain 就放行。
    awk -v route="$route" -v source="$fragment" '
        function trim(value) {
            sub(/^[[:space:]]+/, "", value)
            sub(/[[:space:]]+$/, "", value)
            return value
        }
        function fail(message) {
            printf "%s: %s\n", source, message > "/dev/stderr"
            failed = 1
        }
        function finish_service() {
            if (current_service == "") return
            if (service_chain_count != 1) {
                fail("service " current_service " must reference exactly one " expected_chain)
            }
            current_service = ""
            service_chain_count = 0
        }
        BEGIN {
            expected_chain = "chain-mtcp-" route
            expected_anchor = "mtcp-anchor-" route
        }
        /^services:[[:space:]]*$/ {
            finish_service()
            section = "services"
            services_sections++
            next
        }
        /^chains:[[:space:]]*$/ {
            finish_service()
            section = "chains"
            chains_sections++
            next
        }
        section == "services" && /^- name:[[:space:]]*/ {
            finish_service()
            value = $0
            sub(/^- name:[[:space:]]*/, "", value)
            current_service = trim(value)
            service_count++
            if (current_service == expected_anchor) anchor_count++
            next
        }
        section == "services" && current_service != "" && /^[[:space:]]+chain:[[:space:]]*/ {
            value = $0
            sub(/^[[:space:]]+chain:[[:space:]]*/, "", value)
            value = trim(value)
            service_chain_count++
            if (value != expected_chain) {
                fail("service " current_service " references foreign chain " value "; expected " expected_chain)
            }
            next
        }
        section == "chains" && /^- name:[[:space:]]*/ {
            value = $0
            sub(/^- name:[[:space:]]*/, "", value)
            value = trim(value)
            chain_count++
            if (value == expected_chain) {
                expected_chain_count++
            } else {
                fail("fragment defines foreign chain " value "; expected " expected_chain)
            }
            next
        }
        END {
            finish_service()
            if (services_sections != 1 || chains_sections != 1) {
                fail("must contain exactly one services section and one chains section")
            }
            if (service_count == 0) fail("contains no services")
            if (anchor_count != 1) fail("must contain exactly one " expected_anchor)
            if (chain_count != 1 || expected_chain_count != 1) {
                fail("must define exactly one " expected_chain)
            }
            exit failed
        }
    ' "$fragment" || exit 1
done

output_dir="$(dirname "$OUTPUT")"
mkdir -p "$output_dir"
tmp="$(mktemp "$output_dir/.runtime.yaml.compile.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

emit_section() {
    local wanted="$1" fragment route
    shift
    for fragment in "$@"; do
        route="$(awk '/^# pathlock-route:[[:space:]]*/ { sub(/^# pathlock-route:[[:space:]]*/, ""); print; exit }' "$fragment")"
        [[ -n "$route" ]] || { echo "route marker missing: $fragment" >&2; return 1; }
        printf '  # route: %s\n' "$route"
        awk -v wanted="$wanted" -v source="$fragment" '
            /^services:[[:space:]]*$/ { services++; section="services"; next }
            /^chains:[[:space:]]*$/ { chains++; section="chains"; next }
            /^[A-Za-z][A-Za-z0-9_.-]*:[[:space:]]*$/ &&
                $0 !~ /^services:/ && $0 !~ /^chains:/ { section="other" }
            section == wanted { print }
            END {
                if (services != 1 || chains != 1) {
                    print "invalid route fragment sections: " source > "/dev/stderr"
                    exit 42
                }
            }
        ' "$fragment"
    done
}

{
    echo "# Generated by cn/compile-config.sh. Do not edit; edit instances/*/cn.yaml instead."
    echo "services:"
    emit_section services "$@"
    echo
    echo "chains:"
    emit_section chains "$@"
} > "$tmp"

# GOST 的 service/chain 名称及监听地址在聚合配置内必须唯一；同时确认每个
# service 引用的 chain 都存在，避免重启后才暴露拼装错误。
awk '
    function trim(value) {
        sub(/^[[:space:]]+/, "", value)
        sub(/[[:space:]]+$/, "", value)
        return value
    }
    function remember(kind, value, key) {
        value = trim(value)
        key = kind SUBSEP value
        if (value == "" || seen[key]++) {
            printf "duplicate or empty %s: %s\n", kind, value > "/dev/stderr"
            failed = 1
        }
        return value
    }
    /^services:[[:space:]]*$/ { section="services"; next }
    /^chains:[[:space:]]*$/ { section="chains"; next }
    section == "services" && /^- name:[[:space:]]*/ {
        value=$0; sub(/^- name:[[:space:]]*/, "", value)
        current_service=remember("service", value)
        service_count++
        have_listen=0
        next
    }
    section == "services" && current_service != "" && /^  addr:[[:space:]]*/ && !have_listen {
        value=$0; sub(/^  addr:[[:space:]]*/, "", value); value=trim(value)
        if (listen_seen[value]++) {
            printf "duplicate service listen address: %s\n", value > "/dev/stderr"
            failed = 1
        }
        have_listen=1
        next
    }
    section == "services" && /^[[:space:]]+chain:[[:space:]]*/ {
        value=$0; sub(/^[[:space:]]+chain:[[:space:]]*/, "", value)
        refs[trim(value)]=1
        next
    }
    section == "chains" && /^- name:[[:space:]]*/ {
        value=$0; sub(/^- name:[[:space:]]*/, "", value)
        value=remember("chain", value)
        chains[value]=1
        chain_count++
        next
    }
    section == "chains" && /^      addr:[[:space:]]*/ {
        value=$0; sub(/^      addr:[[:space:]]*/, "", value); value=trim(value)
        if (remote_seen[value]++) {
            printf "duplicate Remote endpoint (route isolation would be ambiguous): %s\n", value > "/dev/stderr"
            failed=1
        }
        next
    }
    END {
        if (service_count == 0 || chain_count == 0) failed=1
        for (name in refs) {
            if (!(name in chains)) {
                printf "service references missing chain: %s\n", name > "/dev/stderr"
                failed=1
            }
        }
        exit failed
    }
' "$tmp"

chmod 0644 "$tmp"
mv -f "$tmp" "$OUTPUT"
trap - EXIT
